version: "3.9"
services:
  redis-7001:
    image: redis:7.0
    command: >
      redis-server
      --port 7001
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 127.0.0.1
      --cluster-announce-port 7001
      --cluster-announce-bus-port 17001
      --appendonly yes
      --protected-mode no
    ports:
      - "7001:7001"
      - "17001:17001"

  redis-7002:
    image: redis:7.0
    command: >
      redis-server
      --port 7002
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 127.0.0.1
      --cluster-announce-port 7002
      --cluster-announce-bus-port 17002
      --appendonly yes
      --protected-mode no
    ports:
      - "7002:7002"
      - "17002:17002"

  redis-7003:
    image: redis:7.0
    command: >
      redis-server
      --port 7003
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 127.0.0.1
      --cluster-announce-port 7003
      --cluster-announce-bus-port 17003
      --appendonly yes
      --protected-mode no
    ports:
      - "7003:7003"
      - "17003:17003"

  redis-7004:
    image: redis:7.0
    command: >
      redis-server
      --port 7004
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 127.0.0.1
      --cluster-announce-port 7004
      --cluster-announce-bus-port 17004
      --appendonly yes
      --protected-mode no
    ports:
      - "7004:7004"
      - "17004:17004"

  redis-7005:
    image: redis:7.0
    command: >
      redis-server
      --port 7005
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 127.0.0.1
      --cluster-announce-port 7005
      --cluster-announce-bus-port 17005
      --appendonly yes
      --protected-mode no
    ports:
      - "7005:7005"
      - "17005:17005"

  redis-7006:
    image: redis:7.0
    command: >
      redis-server
      --port 7006
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip 127.0.0.1
      --cluster-announce-port 7006
      --cluster-announce-bus-port 17006
      --appendonly yes
      --protected-mode no
    ports:
      - "7006:7006"
      - "17006:17006"
